language: go

go:
 - 1.12.x

matrix:
  fast_finish: true

sudo: false

env:
  global:
  - GOBIN=$HOME/bin
  - PATH=$HOME/bin:$PATH
  - GOCACHE=$HOME/.cache/go-build
  - GO111MODULE=on

install:
- go get -t -v -u ./...

script:
- go install ./...
- go test -race -v ./...
