version: "{build}"

os: Windows Server 2012 R2

clone_folder: c:\projects\src\github.com\rjeczalik\interfaces

environment:
 PATH: c:\projects\bin;C:\msys64\mingw64\bin;%PATH%
 GOPATH: c:\projects
 GOVERSION: 1.12.4
 GOCACHE: c:\gocache
 GO111MODULE: on

install:
 - rmdir c:\go /s /q
 - appveyor DownloadFile https://storage.googleapis.com/golang/go%GOVERSION%.windows-amd64.zip
 - 7z x go%GOVERSION%.windows-amd64.zip -y -oC:\ > NUL

 - cd %APPVEYOR_BUILD_FOLDER%
 - go version
 - go get -v -t ./...

build_script:
 - go install ./...
 - go test -race -v ./...

test: off

deploy: off
